version: '{build}'

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

skip_commits:
  files:
    - README.md

image:
  - Visual Studio 2017

build_script:
  - ps: |
      dotnet build -c Release
      if ($env:APPVEYOR_REPO_TAG -eq $true) {
          dotnet pack -c Release --no-build -p:Version=$($env:APPVEYOR_REPO_TAG_NAME.Substring(1))
      }

test: off

artifacts:
  - path: '**\*.nupkg'

deploy:
  - provider: NuGet
    api_key: $(NUGET_API_KEY)
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true